version: '3'
services:
  wordpress:
    build: .
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: mariadb.railway.internal
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: railway
WORDPRESS_DB_HOST=mariadb.railway.internal
WORDPRESS_DB_USER=root
WORDPRESS_DB_PASSWORD=tu_password
WORDPRESS_DB_NAME=railway